((nil . ((indent-tabs-mode . nil)
         (tab-width . 2)))
 (makefile-mode . ((indent-tabs-mode . t)))
 (rust-mode . ((rust-indent-offset . 2)))
 (rust-ts-mode . ((rust-indent-offset . 2)))
 (js-mode . ((js-indent-level . 2)))
 (js-ts-mode . ((js-indent-level . 2)))
 (typescript-mode . ((typescript-indent-level . 2)))
 (typescript-ts-mode . ((typescript-ts-mode-indent-offset . 2)))
 (css-mode . ((css-indent-offset . 2)))
 (json-mode . ((js-indent-level . 2)))
 (html-mode . ((sgml-basic-offset . 2)))
 (web-mode . ((web-mode-markup-indent-offset . 2)
              (web-mode-css-indent-offset . 2)
              (web-mode-code-indent-offset . 2))))
